---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 188893
custom_fields:
- keyname: reporter_notice
  field_type: copyable
  name: Attention!
  value: https://github.com/eden881/trmnl-teslamate-reporter
  description: This plugin depends on data reporting from your local Teslamate deployment. Head over to this URL to deploy the reporter alongside Teslamate!
name: Tessie
refresh_interval: 30
